name: Validate Pull Request

on: [push, pull_request]

jobs:
  lint:
    name: Lint lockdir, generate opam files, autoformat
    runs-on: macos-latest
    steps:
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Install esy
        run: npm install -g esy
      - name: Setup Git to push back
        run: |
          git remote set-url --push origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git config user.name "Github Runner"
          git config user.email "runner@runner.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update lockdir
        run: |
          esy install
          esy install -P test
          esy install -P bench
          esy install -P doc
          esy install -P js
          esy install -P examples
          git diff --exit-code || (git add *lock; git commit -m "Update lockdir, ")
      - name: Push if it is not up to date
        if: github.event_name != 'pull_request'
        run: |
          # if last commit is from the bot then push.
          [[ "$(git log -1 --pretty=format:'%an')" != "Github Runner" ]] || git push origin HEAD:$GITHUB_REF
      - name: Display status should be clean
        if: always()
        run: |
          git status
          git log -2
          git diff
      - uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (require("child_process").execSync("git log -1 --pretty=format:'%an'") == "Github Runner")
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "I have updated your lock dirs and formatted the code.\n" +
                  "Please @" + context.actor + " pull the last commit before pushing any more changes."
              });
